import Head from "next/head";
import { useContext } from "react";
import Home from "../components/home/Home";
import Login from "../components/login/Login";
import { LoginContext } from "../store/login-ctx";

import styles from "../styles/Homepage.module.css";

export default function Homepage() {
	const loginCtx = useContext(LoginContext);

	return (
		<div>
			<Head>
				<title>fam - Technopartner</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				{loginCtx.isLoggedIn ? <Home /> : <Login />}
			</main>
		</div>
	);
}
